// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6zmVxrW1xI3BWQOyOUYmwa4yfZ5hSijU',
    appId: '1:77449226628:web:03d90d39a4fa6891ea95d1',
    messagingSenderId: '77449226628',
    projectId: 'phonebook-a9542',
    authDomain: 'phonebook-a9542.firebaseapp.com',
    storageBucket: 'phonebook-a9542.firebasestorage.app',
    measurementId: 'G-HTB8KBJ9HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFum6_ck5P4u6eXmY6aTb_Aw_50WBB_5I',
    appId: '1:77449226628:android:e349f15eaaff01deea95d1',
    messagingSenderId: '77449226628',
    projectId: 'phonebook-a9542',
    storageBucket: 'phonebook-a9542.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOlEp869K3ndD22sKaLf1r1zYbZb-wMtA',
    appId: '1:77449226628:ios:d55a7ce03be8e7f4ea95d1',
    messagingSenderId: '77449226628',
    projectId: 'phonebook-a9542',
    storageBucket: 'phonebook-a9542.firebasestorage.app',
    iosBundleId: 'com.example.sabaca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOlEp869K3ndD22sKaLf1r1zYbZb-wMtA',
    appId: '1:77449226628:ios:d55a7ce03be8e7f4ea95d1',
    messagingSenderId: '77449226628',
    projectId: 'phonebook-a9542',
    storageBucket: 'phonebook-a9542.firebasestorage.app',
    iosBundleId: 'com.example.sabaca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6zmVxrW1xI3BWQOyOUYmwa4yfZ5hSijU',
    appId: '1:77449226628:web:03d90d39a4fa6891ea95d1',
    messagingSenderId: '77449226628',
    projectId: 'phonebook-a9542',
    authDomain: 'phonebook-a9542.firebaseapp.com',
    storageBucket: 'phonebook-a9542.firebasestorage.app',
    measurementId: 'G-HTB8KBJ9HM',
  );
}
